"""Portable PDF invoice renderer via reportlab (pure Python, no system deps).

Kept intentionally minimal — clean, printable, sage-primary accents.
"""
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.pdfgen.canvas import Canvas


SAGE = colors.HexColor("#5C8C6F")
CHARCOAL = colors.HexColor("#2A332B")
MUTED = colors.HexColor("#8B9291")


def _money(cents: int, currency: str = "USD") -> str:
    prefix = "$" if currency == "USD" else f"{currency} "
    return f"{prefix}{(cents or 0) / 100:.2f}"


def render_invoice_pdf(invoice: dict) -> bytes:
    buf = BytesIO()
    c = Canvas(buf, pagesize=LETTER)
    width, height = LETTER

    # ---- Header brand ----
    c.setFillColor(SAGE)
    c.rect(0, height - 0.6 * inch, width, 0.6 * inch, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(0.75 * inch, height - 0.4 * inch, "OnCall Foot")
    c.setFont("Helvetica", 10)
    c.drawRightString(width - 0.75 * inch, height - 0.4 * inch, "Invoice")

    # ---- Title block ----
    y = height - 1.2 * inch
    c.setFillColor(CHARCOAL)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(0.75 * inch, y, f"Invoice {invoice.get('invoice_number', '')}")
    y -= 0.28 * inch
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 10)
    c.drawString(0.75 * inch, y, f"Issued {invoice.get('issued_at', '')[:10]}   ·   Status: {invoice.get('status', 'issued').upper()}")

    # ---- Provider / Client blocks ----
    y -= 0.5 * inch
    provider_name = invoice.get("provider_name") or "Provider"
    client = invoice.get("client") or {}

    c.setFillColor(MUTED)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(0.75 * inch, y, "FROM")
    c.drawString(4.0 * inch, y, "BILLED TO")

    c.setFillColor(CHARCOAL)
    c.setFont("Helvetica-Bold", 12)
    y -= 0.22 * inch
    c.drawString(0.75 * inch, y, provider_name)
    c.drawString(4.0 * inch, y, client.get("name") or "Client")

    c.setFont("Helvetica", 10)
    c.setFillColor(CHARCOAL)
    y -= 0.2 * inch
    if client.get("phone"):
        c.drawString(4.0 * inch, y, client["phone"])
    y -= 0.18 * inch
    if client.get("address"):
        c.drawString(4.0 * inch, y, client["address"][:60])
    y -= 0.18 * inch
    if client.get("pincode"):
        c.drawString(4.0 * inch, y, client["pincode"])

    # ---- Line items ----
    y -= 0.4 * inch
    c.setFillColor(SAGE)
    c.line(0.75 * inch, y, width - 0.75 * inch, y)
    y -= 0.22 * inch
    c.setFillColor(MUTED)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(0.75 * inch, y, "DESCRIPTION")
    c.drawRightString(5.5 * inch, y, "QTY")
    c.drawRightString(6.5 * inch, y, "UNIT")
    c.drawRightString(width - 0.75 * inch, y, "TOTAL")
    y -= 0.15 * inch
    c.setStrokeColor(colors.HexColor("#E5E5E5"))
    c.line(0.75 * inch, y, width - 0.75 * inch, y)

    currency = invoice.get("currency", "USD")
    c.setFillColor(CHARCOAL)
    c.setFont("Helvetica", 11)
    for item in invoice.get("line_items", []):
        y -= 0.28 * inch
        c.drawString(0.75 * inch, y, item.get("description", "")[:60])
        c.drawRightString(5.5 * inch, y, str(item.get("quantity", 1)))
        c.drawRightString(6.5 * inch, y, _money(item.get("unit_price_cents", 0), currency))
        c.drawRightString(width - 0.75 * inch, y, _money(item.get("total_cents", 0), currency))

    # ---- Totals ----
    y -= 0.5 * inch
    c.setStrokeColor(colors.HexColor("#E5E5E5"))
    c.line(4.5 * inch, y, width - 0.75 * inch, y)
    y -= 0.25 * inch
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 10)
    c.drawRightString(6.5 * inch, y, "Subtotal")
    c.setFillColor(CHARCOAL)
    c.drawRightString(width - 0.75 * inch, y, _money(invoice.get("subtotal_cents", 0), currency))
    y -= 0.22 * inch
    c.setFillColor(MUTED)
    c.drawRightString(6.5 * inch, y, "Tax")
    c.setFillColor(CHARCOAL)
    c.drawRightString(width - 0.75 * inch, y, _money(invoice.get("tax_cents", 0), currency))
    y -= 0.35 * inch
    c.setFillColor(SAGE)
    c.setFont("Helvetica-Bold", 14)
    c.drawRightString(6.5 * inch, y, "TOTAL")
    c.drawRightString(width - 0.75 * inch, y, _money(invoice.get("total_cents", 0), currency))

    # ---- Footer ----
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 9)
    c.drawString(0.75 * inch, 0.6 * inch, "Thank you. Generated by OnCall Foot.")
    c.drawRightString(width - 0.75 * inch, 0.6 * inch, invoice.get("invoice_number", ""))

    c.showPage()
    c.save()
    return buf.getvalue()
